apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-10-30T19:50:31Z"
  name: carts-canary
  resourceVersion: "6090"
  selfLink: /api/v1/namespaces/sockshop-staging/services/carts
  uid: 87808656-fb4e-11e9-aadd-42010a800133
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
