---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-10-31T08:28:12Z"
  name: carts-canary
  resourceVersion: "175549"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: 60c9fd19-fbb8-11e9-aadd-42010a800133
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
