apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-10-31T08:22:50Z"
  name: carts-primary
  resourceVersion: "174310"
  selfLink: /api/v1/namespaces/sockshop-staging/services/carts
  uid: a0af584d-fbb7-11e9-aadd-42010a800133
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts-primary
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
